services:
  server:
    image: grpc-solution-server
    build:
      context: ./messenger
      dockerfile: server.dockerfile
    environment:
      MESSENGER_SERVER_PORT: 51075
    ports:
      - 51075:51075

  client:
    image: grpc-solution-client
    build:
      context: ./messenger
      dockerfile: client.dockerfile
    environment:
      MESSENGER_SERVER_ADDR: server:51075
      MESSENGER_HTTP_PORT: 8080
    ports:
      - 8080:8080